PROG=proj


SRCS = proj.c timer.c keyboard.c mouse.c videoCard.c sprite.c game.c leaderboard.c menu.c rtc.c serialPort.c utility.c files.c

CPPFLAGS += -pedantic #-D __LCOM_OPTIMIZED__


DPADD += ${LIBLCF}

LDADD += -llcf



.include <minix.lcom.mk>
