PROG=lab5 



SRCS = lab5.c keyboard.c timer.c graphics.c sprite.c



CPPFLAGS += -pedantic -DLAB5



DPADD += ${LIBLCF} ${LIBLM}
LDADD += -llcf -llm



.include <minix.lcom.mk>
# DO NOT DELETE
